// @generated automatically by Diesel CLI.

pub mod game {
    diesel::table! {
        /// Representation of the `game.attributes` table.
        ///
        /// (Automatically generated by Diesel.)
        game.attributes (id) {
            /// The `id` column of the `game.attributes` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `name` column of the `game.attributes` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `description` column of the `game.attributes` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            description -> Text,
            /// The `created_at` column of the `game.attributes` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.attributes` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::table! {
        /// Representation of the `game.currency` table.
        ///
        /// (Automatically generated by Diesel.)
        game.currency (id) {
            /// The `id` column of the `game.currency` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `world_id` column of the `game.currency` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            world_id -> Int8,
            /// The `code` column of the `game.currency` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            code -> Varchar,
            /// The `name` column of the `game.currency` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `description` column of the `game.currency` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            description -> Text,
            /// The `is_spendable` column of the `game.currency` table.
            ///
            /// Its SQL type is `Bool`.
            ///
            /// (Automatically generated by Diesel.)
            is_spendable -> Bool,
            /// The `created_at` column of the `game.currency` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.currency` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::table! {
        /// Representation of the `game.enemies` table.
        ///
        /// (Automatically generated by Diesel.)
        game.enemies (id) {
            /// The `id` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `world_id` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            world_id -> Int8,
            /// The `code` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            code -> Varchar,
            /// The `name` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `description` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            description -> Text,
            /// The `class` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            class -> Varchar,
            /// The `level` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            level -> Int4,
            /// The `hit_points` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            hit_points -> Int4,
            /// The `stamina` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            stamina -> Int4,
            /// The `strength` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            strength -> Int4,
            /// The `dexterity` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            dexterity -> Int4,
            /// The `constitution` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            constitution -> Int4,
            /// The `intelligence` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            intelligence -> Int4,
            /// The `wisdom` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            wisdom -> Int4,
            /// The `weapons` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Jsonb`.
            ///
            /// (Automatically generated by Diesel.)
            weapons -> Jsonb,
            /// The `armor` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Jsonb`.
            ///
            /// (Automatically generated by Diesel.)
            armor -> Jsonb,
            /// The `created_at` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.enemies` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::table! {
        /// Representation of the `game.feats` table.
        ///
        /// (Automatically generated by Diesel.)
        game.feats (id) {
            /// The `id` column of the `game.feats` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `world_id` column of the `game.feats` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            world_id -> Int8,
            /// The `code` column of the `game.feats` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            code -> Varchar,
            /// The `name` column of the `game.feats` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `description` column of the `game.feats` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            description -> Text,
            /// The `created_at` column of the `game.feats` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.feats` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::table! {
        /// Representation of the `game.item_categories` table.
        ///
        /// (Automatically generated by Diesel.)
        game.item_categories (id) {
            /// The `id` column of the `game.item_categories` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `parent_id` column of the `game.item_categories` table.
            ///
            /// Its SQL type is `Nullable<Int8>`.
            ///
            /// (Automatically generated by Diesel.)
            parent_id -> Nullable<Int8>,
            /// The `name` column of the `game.item_categories` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `description` column of the `game.item_categories` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            description -> Text,
            /// The `created_at` column of the `game.item_categories` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.item_categories` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::table! {
        /// Representation of the `game.items` table.
        ///
        /// (Automatically generated by Diesel.)
        game.items (id) {
            /// The `id` column of the `game.items` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `category_id` column of the `game.items` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            category_id -> Int8,
            /// The `name` column of the `game.items` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `description` column of the `game.items` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            description -> Text,
            /// The `item_properties` column of the `game.items` table.
            ///
            /// Its SQL type is `Jsonb`.
            ///
            /// (Automatically generated by Diesel.)
            item_properties -> Jsonb,
            /// The `created_at` column of the `game.items` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.items` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
            /// The `item_type` column of the `game.items` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            item_type -> Varchar,
            /// The `code` column of the `game.items` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            code -> Varchar,
            /// The `base_price` column of the `game.items` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            base_price -> Int8,
            /// The `world_id` column of the `game.items` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            world_id -> Int8,
        }
    }

    diesel::table! {
        /// Representation of the `game.npc_spawn_rules` table.
        ///
        /// (Automatically generated by Diesel.)
        game.npc_spawn_rules (id) {
            /// The `id` column of the `game.npc_spawn_rules` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `npc_template_id` column of the `game.npc_spawn_rules` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            npc_template_id -> Int8,
            /// The `world_node_id` column of the `game.npc_spawn_rules` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            world_node_id -> Int8,
            /// The `spawn_chance` column of the `game.npc_spawn_rules` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            spawn_chance -> Int4,
            /// The `spawn_quantity_min` column of the `game.npc_spawn_rules` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            spawn_quantity_min -> Int4,
            /// The `spawn_quantity_max` column of the `game.npc_spawn_rules` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            spawn_quantity_max -> Int4,
            /// The `created_at` column of the `game.npc_spawn_rules` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.npc_spawn_rules` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::table! {
        /// Representation of the `game.npc_templates` table.
        ///
        /// (Automatically generated by Diesel.)
        game.npc_templates (id) {
            /// The `id` column of the `game.npc_templates` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `name` column of the `game.npc_templates` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `description` column of the `game.npc_templates` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            description -> Text,
            /// The `npc_properties` column of the `game.npc_templates` table.
            ///
            /// Its SQL type is `Jsonb`.
            ///
            /// (Automatically generated by Diesel.)
            npc_properties -> Jsonb,
            /// The `can_spawn_multiple` column of the `game.npc_templates` table.
            ///
            /// Its SQL type is `Bool`.
            ///
            /// (Automatically generated by Diesel.)
            can_spawn_multiple -> Bool,
            /// The `can_respawn` column of the `game.npc_templates` table.
            ///
            /// Its SQL type is `Bool`.
            ///
            /// (Automatically generated by Diesel.)
            can_respawn -> Bool,
            /// The `created_at` column of the `game.npc_templates` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.npc_templates` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::table! {
        /// Representation of the `game.races` table.
        ///
        /// (Automatically generated by Diesel.)
        game.races (id) {
            /// The `id` column of the `game.races` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `world_id` column of the `game.races` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            world_id -> Int8,
            /// The `code` column of the `game.races` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            code -> Varchar,
            /// The `name` column of the `game.races` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `description` column of the `game.races` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            description -> Text,
            /// The `created_at` column of the `game.races` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.races` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::table! {
        /// Representation of the `game.skills` table.
        ///
        /// (Automatically generated by Diesel.)
        game.skills (id) {
            /// The `id` column of the `game.skills` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `world_id` column of the `game.skills` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            world_id -> Int8,
            /// The `code` column of the `game.skills` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            code -> Varchar,
            /// The `name` column of the `game.skills` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `description` column of the `game.skills` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            description -> Text,
            /// The `created_at` column of the `game.skills` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.skills` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::table! {
        /// Representation of the `game.world_node_features` table.
        ///
        /// (Automatically generated by Diesel.)
        game.world_node_features (id) {
            /// The `id` column of the `game.world_node_features` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `world_node_id` column of the `game.world_node_features` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            world_node_id -> Int8,
            /// The `feature_name` column of the `game.world_node_features` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            feature_name -> Varchar,
            /// The `feature_value` column of the `game.world_node_features` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            feature_value -> Text,
            /// The `feature_properties` column of the `game.world_node_features` table.
            ///
            /// Its SQL type is `Jsonb`.
            ///
            /// (Automatically generated by Diesel.)
            feature_properties -> Jsonb,
            /// The `created_at` column of the `game.world_node_features` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.world_node_features` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::table! {
        /// Representation of the `game.world_nodes` table.
        ///
        /// (Automatically generated by Diesel.)
        game.world_nodes (id) {
            /// The `id` column of the `game.world_nodes` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `parent_id` column of the `game.world_nodes` table.
            ///
            /// Its SQL type is `Nullable<Int8>`.
            ///
            /// (Automatically generated by Diesel.)
            parent_id -> Nullable<Int8>,
            /// The `name` column of the `game.world_nodes` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `description` column of the `game.world_nodes` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            description -> Text,
            /// The `created_at` column of the `game.world_nodes` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.world_nodes` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
            /// The `world_id` column of the `game.world_nodes` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            world_id -> Int8,
        }
    }

    diesel::table! {
        /// Representation of the `game.worlds` table.
        ///
        /// (Automatically generated by Diesel.)
        game.worlds (id) {
            /// The `name` column of the `game.worlds` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `description` column of the `game.worlds` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            description -> Text,
            /// The `created_at` column of the `game.worlds` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `game.worlds` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
            /// The `id` column of the `game.worlds` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `code` column of the `game.worlds` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            code -> Varchar,
        }
    }

    diesel::joinable!(currency -> worlds (world_id));
    diesel::joinable!(enemies -> worlds (world_id));
    diesel::joinable!(feats -> worlds (world_id));
    diesel::joinable!(items -> item_categories (category_id));
    diesel::joinable!(items -> worlds (world_id));
    diesel::joinable!(npc_spawn_rules -> npc_templates (npc_template_id));
    diesel::joinable!(npc_spawn_rules -> world_nodes (world_node_id));
    diesel::joinable!(races -> worlds (world_id));
    diesel::joinable!(skills -> worlds (world_id));
    diesel::joinable!(world_node_features -> world_nodes (world_node_id));
    diesel::joinable!(world_nodes -> worlds (world_id));

    diesel::allow_tables_to_appear_in_same_query!(
        attributes,
        currency,
        enemies,
        feats,
        item_categories,
        items,
        npc_spawn_rules,
        npc_templates,
        races,
        skills,
        world_node_features,
        world_nodes,
        worlds,
    );
}
