// @generated automatically by Diesel CLI.

pub mod system {
    diesel::table! {
        /// Representation of the `system.settings` table.
        ///
        /// (Automatically generated by Diesel.)
        system.settings (id) {
            /// The `id` column of the `system.settings` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `name` column of the `system.settings` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `data_type` column of the `system.settings` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            data_type -> Varchar,
            /// The `value` column of the `system.settings` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            value -> Text,
            /// The `created_at` column of the `system.settings` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `system.settings` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::table! {
        /// Representation of the `system.users` table.
        ///
        /// (Automatically generated by Diesel.)
        system.users (id) {
            /// The `id` column of the `system.users` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `username` column of the `system.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            username -> Varchar,
            /// The `password` column of the `system.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            password -> Varchar,
            /// The `email` column of the `system.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            email -> Varchar,
            /// The `full_name` column of the `system.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            full_name -> Varchar,
            /// The `created_at` column of the `system.users` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `system.users` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::allow_tables_to_appear_in_same_query!(
        settings,
        users,
    );
}
