// @generated automatically by Diesel CLI.

pub mod system {
    diesel::table! {
        /// Representation of the `system.permissions` table.
        ///
        /// (Automatically generated by Diesel.)
        system.permissions (id) {
            /// The `id` column of the `system.permissions` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `code` column of the `system.permissions` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            code -> Varchar,
            /// The `name` column of the `system.permissions` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            name -> Varchar,
            /// The `description` column of the `system.permissions` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            description -> Text,
            /// The `created_at` column of the `system.permissions` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `created_by` column of the `system.permissions` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            created_by -> Varchar,
            /// The `updated_at` column of the `system.permissions` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
            /// The `updated_by` column of the `system.permissions` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            updated_by -> Varchar,
        }
    }

    diesel::table! {
        /// Representation of the `system.role_permissions` table.
        ///
        /// (Automatically generated by Diesel.)
        system.role_permissions (id) {
            /// The `id` column of the `system.role_permissions` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `role_id` column of the `system.role_permissions` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            role_id -> Int8,
            /// The `permission_id` column of the `system.role_permissions` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            permission_id -> Int8,
            /// The `created_at` column of the `system.role_permissions` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `created_by` column of the `system.role_permissions` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            created_by -> Varchar,
            /// The `updated_at` column of the `system.role_permissions` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
            /// The `updated_by` column of the `system.role_permissions` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            updated_by -> Varchar,
        }
    }

    diesel::table! {
        /// Representation of the `system.roles` table.
        ///
        /// (Automatically generated by Diesel.)
        system.roles (id) {
            /// The `id` column of the `system.roles` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `name` column of the `system.roles` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            name -> Varchar,
            /// The `description` column of the `system.roles` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            description -> Varchar,
            /// The `created_at` column of the `system.roles` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamptz,
            /// The `updated_at` column of the `system.roles` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamptz,
        }
    }

    diesel::table! {
        /// Representation of the `system.settings` table.
        ///
        /// (Automatically generated by Diesel.)
        system.settings (id) {
            /// The `name` column of the `system.settings` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `data_type` column of the `system.settings` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            data_type -> Varchar,
            /// The `value` column of the `system.settings` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            value -> Text,
            /// The `created_at` column of the `system.settings` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `system.settings` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
            /// The `id` column of the `system.settings` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
        }
    }

    diesel::table! {
        /// Representation of the `system.user_api_keys` table.
        ///
        /// (Automatically generated by Diesel.)
        system.user_api_keys (id) {
            /// The `id` column of the `system.user_api_keys` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `user_id` column of the `system.user_api_keys` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            user_id -> Int8,
            /// The `key_type` column of the `system.user_api_keys` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            key_type -> Varchar,
            /// The `api_key` column of the `system.user_api_keys` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            api_key -> Varchar,
            /// The `private_key` column of the `system.user_api_keys` table.
            ///
            /// Its SQL type is `Nullable<Varchar>`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            private_key -> Nullable<Varchar>,
            /// The `expiration` column of the `system.user_api_keys` table.
            ///
            /// Its SQL type is `Nullable<Timestamp>`.
            ///
            /// (Automatically generated by Diesel.)
            expiration -> Nullable<Timestamp>,
            /// The `created_at` column of the `system.user_api_keys` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `created_by` column of the `system.user_api_keys` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            created_by -> Varchar,
            /// The `updated_at` column of the `system.user_api_keys` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
            /// The `updated_by` column of the `system.user_api_keys` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            updated_by -> Varchar,
        }
    }

    diesel::table! {
        /// Representation of the `system.user_roles` table.
        ///
        /// (Automatically generated by Diesel.)
        system.user_roles (id) {
            /// The `id` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `user_id` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            user_id -> Int8,
            /// The `role_id` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            role_id -> Int8,
            /// The `is_read_only` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Bool`.
            ///
            /// (Automatically generated by Diesel.)
            is_read_only -> Bool,
            /// The `start_date` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            start_date -> Timestamptz,
            /// The `end_date` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            end_date -> Nullable<Timestamptz>,
            /// The `created_at` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamptz,
            /// The `updated_at` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamptz,
        }
    }

    diesel::table! {
        /// Representation of the `system.users` table.
        ///
        /// (Automatically generated by Diesel.)
        system.users (id) {
            /// The `username` column of the `system.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            username -> Varchar,
            /// The `password` column of the `system.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            password -> Varchar,
            /// The `email` column of the `system.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            email -> Varchar,
            /// The `full_name` column of the `system.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            full_name -> Varchar,
            /// The `created_at` column of the `system.users` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `system.users` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
            /// The `id` column of the `system.users` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
        }
    }

    diesel::joinable!(role_permissions -> permissions (permission_id));
    diesel::joinable!(role_permissions -> roles (role_id));
    diesel::joinable!(user_api_keys -> users (user_id));
    diesel::joinable!(user_roles -> roles (role_id));
    diesel::joinable!(user_roles -> users (user_id));

    diesel::allow_tables_to_appear_in_same_query!(
        permissions,
        role_permissions,
        roles,
        settings,
        user_api_keys,
        user_roles,
        users,
    );
}
