// @generated automatically by Diesel CLI.

pub mod system {
    diesel::table! {
        /// Representation of the `system.roles` table.
        ///
        /// (Automatically generated by Diesel.)
        system.roles (id) {
            /// The `id` column of the `system.roles` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `name` column of the `system.roles` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            name -> Varchar,
            /// The `description` column of the `system.roles` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            description -> Varchar,
            /// The `created_at` column of the `system.roles` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamptz,
            /// The `updated_at` column of the `system.roles` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamptz,
        }
    }

    diesel::table! {
        /// Representation of the `system.settings` table.
        ///
        /// (Automatically generated by Diesel.)
        system.settings (id) {
            /// The `id` column of the `system.settings` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `name` column of the `system.settings` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            name -> Varchar,
            /// The `data_type` column of the `system.settings` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            data_type -> Varchar,
            /// The `value` column of the `system.settings` table.
            ///
            /// Its SQL type is `Text`.
            ///
            /// (Automatically generated by Diesel.)
            value -> Text,
            /// The `created_at` column of the `system.settings` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `system.settings` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
        }
    }

    diesel::table! {
        /// Representation of the `system.user_roles` table.
        ///
        /// (Automatically generated by Diesel.)
        system.user_roles (id) {
            /// The `id` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
            /// The `user_id` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            user_id -> Int8,
            /// The `role_id` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            role_id -> Int8,
            /// The `is_read_only` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Bool`.
            ///
            /// (Automatically generated by Diesel.)
            is_read_only -> Bool,
            /// The `start_date` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            start_date -> Timestamptz,
            /// The `end_date` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            end_date -> Nullable<Timestamptz>,
            /// The `created_at` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamptz,
            /// The `updated_at` column of the `system.user_roles` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamptz,
        }
    }

    diesel::table! {
        /// Representation of the `system.users` table.
        ///
        /// (Automatically generated by Diesel.)
        system.users (id) {
            /// The `username` column of the `system.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            username -> Varchar,
            /// The `password` column of the `system.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            password -> Varchar,
            /// The `email` column of the `system.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            email -> Varchar,
            /// The `full_name` column of the `system.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            full_name -> Varchar,
            /// The `created_at` column of the `system.users` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamp,
            /// The `updated_at` column of the `system.users` table.
            ///
            /// Its SQL type is `Timestamp`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamp,
            /// The `id` column of the `system.users` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int8,
        }
    }

    diesel::joinable!(user_roles -> roles (role_id));
    diesel::joinable!(user_roles -> users (user_id));

    diesel::allow_tables_to_appear_in_same_query!(
        roles,
        settings,
        user_roles,
        users,
    );
}
