# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.system]
file = "server/src/db/system_schema.rs"
with_docs = true 
schema = "system"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]


[print_schema.game]
file = "server/src/db/game_schema.rs"
with_docs = true 
schema = "game"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[print_schema.player]
file = "server/src/db/player_schema.rs"
with_docs = true 
schema = "player"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]


[migrations_directory]
dir = "/Users/scott/source/github/ssargent/mud/migrations"
