// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrUpdateSetting(ctx context.Context, db DBTX, arg *CreateOrUpdateSettingParams) (*SystemSetting, error)
	// Users
	CreateUser(ctx context.Context, db DBTX, arg *CreateUserParams) (*SystemUser, error)
	DeleteSettingByName(ctx context.Context, db DBTX, name string) error
	GetSettingByID(ctx context.Context, db DBTX, id uuid.UUID) (*SystemSetting, error)
	// System
	GetSettingByName(ctx context.Context, db DBTX, name string) (*SystemSetting, error)
	GetSettings(ctx context.Context, db DBTX) ([]*SystemSetting, error)
	GetUserByID(ctx context.Context, db DBTX, id uuid.UUID) (*SystemUser, error)
	GetUserByUsername(ctx context.Context, db DBTX, username string) (*SystemUser, error)
}

var _ Querier = (*Queries)(nil)
