[package]
name = "server"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_derive.workspace = true
protocol.workspace = true

chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "2.2.0", features = [
    "postgres",
    "uuid",
    "chrono",
    "serde_json",
    "r2d2",
] }
# build libpq and openssl as part of the build process
# uncomment these lines if you run into setup issues
# pq-sys = { version = "0.6", features = ["bundled"] }
# openssl-sys = { version = "0.9.100", features = ["vendored"] } 
dotenvy = "0.15"
diesel-derive-enum = "1.0"
axum = { version = "0.7.9", features = ["tracing"] }
tower = "0.5.2"
tokio = { version = "1.42.0", features = ["full", "rt-multi-thread"] }
hyper = "0.14"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tower-http = { version = "0.6.1", features = ["trace"] }
jsonwebtoken = "9.3.1"
bcrypt = "0.17.0"
rand = "0.8"
base32 = "0.5.1"
sha3 = "0.10.8"
pbkdf2 = "0.12.2"
base64 = "0.22.1"
